version: 0.2
env:
  variables:
    NODE_OPTIONS: '--max-old-space-size=4096'
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - mkdir ~/.aws
      - echo "[profile account-role]\nrole_arn = ${ACCOUNT_ROLE}\ncredential_source = EcsContainer" >> ~/.aws/config
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -Dnative=true
      - $(aws cloudformation describe-stacks --profile account-role --stack-name $VPC_STACK_NAME | jq -r ".Stacks[].Outputs | map(\"export \(.OutputKey)=\(.OutputValue|tostring)\")|.[]")
      - sam deploy --profile account-role --stack-name $STACK_NAME --s3-bucket $LAMBDA_BUCKET_NAME --s3-prefix $ENV-$STACK_NAME --capabilities CAPABILITY_IAM --parameter-overrides VpcId=$VPC MountTarget1Subnet=$QUTPrivateSubnet1 MountTarget2Subnet=$QUTPrivateSubnet2 MountTarget3Subnet=$QUTPrivateSubnet3
