package au.qut.edu.eresearch.serverlesssearch.service;

import org.apache.solr.core.CoreContainer;
import org.junit.jupiter.api.Test;

import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Date;

public class ContainerTest {

    @Test
    public void initialise() throws Exception {
        final Path solrHome = Paths.get("target", "index", "solr");
        final Path lib = solrHome.resolve("lib");
        if (!Files.isDirectory(lib)) {
            Files.createDirectories(lib);
        }
        final Path solrXml = solrHome.resolve("solr.xml");
        if (!Files.exists(solrXml)) {
            try (PrintStream writer = new PrintStream(Files.newOutputStream(solrXml, StandardOpenOption.CREATE))) {
                writer.printf("<!-- Generated by %s on %tF %<tT -->%n", getClass().getSimpleName(), new Date());
                writer.println("<solr>");
                writer.printf("  <str name=\"%s\">%s</str>%n", "sharedLib", solrHome.relativize(lib));
                writer.println("</solr>");
            }
        }
        CoreContainer coreContainer = CoreContainer.createAndLoad(solrHome, solrXml);


    }
}
